# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4de7c2757648fafcb364173aaf8e4bb192cfa64b77e052ff7a6f473f72039c3e2a5af917c3c48da286acd32cbbeac7d18491fd81fba14e4648fba43dacf670a

test:
  secret_key_base: c3c1e1344bd75eff69792e0e42b64f4729e1bc869fc9505362f4360d4cedf1be840e1f1967e558ad41d8a84576497e90dc12da9b4e1590289e339ca70c2dc858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
